/* AUTO-GENERATED by tools/generate_wire.py from shared/wire_contract.json - DO NOT EDIT. */
#pragma once
#include <stdint.h>
#ifdef __cplusplus
extern "C" {
#endif

#define ANIM_CLUSTER_ID 0x1618FC01
#define ANIM_ATTR_MATRIX_WIDTH 0x0000
#define ANIM_ATTR_MATRIX_HEIGHT 0x0001
#define ANIM_ATTR_PIXEL_COUNT 0x0002
#define ANIM_ATTR_SERPENTINE 0x0003
#define ANIM_ATTR_CACHED 0x0004
#define ANIM_ATTR_TRANSFER_HASH 0x0005
#define ANIM_ATTR_TRANSFER_META 0x0006
#define ANIM_ATTR_FRAME_CHUNK 0x0007
#define ANIM_ATTR_STATUS 0x0008
#define ANIM_ATTR_PLAY_CMD 0x0009
#define ANIM_ATTR_ACTIVE 0x000A
#define ANIM_CHUNK_MAX_BYTES 1000

typedef struct {
    uint16_t frame_index;
    uint8_t count;
    uint8_t width;
    uint8_t height;
    uint8_t fps;
} anim_chunk_hdr_t;

typedef struct {
    uint16_t total_frames;
    uint8_t fps;
    uint8_t loop;
    uint8_t width;
    uint8_t height;
} anim_transfer_meta_t;

#ifdef __cplusplus
}
#endif
