#!/usr/bin/env python3
"""Generate the C and Python wire-contract definitions from shared/wire_contract.json.

Single source of truth for the animation wire protocol (cluster/attribute IDs,
chunk/meta byte layout, max chunk size) shared between the ESP32 firmware and
the companion Python tool (tools/effects.py).

Outputs:
  components/animation/include/anim_protocol.h   (C)
  tools/matter_anim/protocol.py                  (Python)

Run from the repo root:  python3 tools/generate_wire.py
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCHEMA = os.path.join(ROOT, "shared", "wire_contract.json")
C_OUT = os.path.join(ROOT, "components", "animation", "include", "anim_protocol.h")
PY_OUT = os.path.join(ROOT, "tools", "matter_anim", "protocol.py")

C_TYPES = {"u8": "uint8_t", "u16": "uint16_t", "u32": "uint32_t"}
PY_FMT = {"u8": "B", "u16": "H", "u32": "I"}


def _c_struct(name, fields):
    lines = [f"typedef struct {{"]
    for fname, ftype in fields:
        lines.append(f"    {C_TYPES[ftype]} {fname};")
    lines.append(f"}} {name};")
    return "\n".join(lines)


def generate(schema):
    attrs = schema["attributes"]
    c_lines = [
        "/* AUTO-GENERATED by tools/generate_wire.py from shared/wire_contract.json - DO NOT EDIT. */",
        "#pragma once",
        "#include <stdint.h>",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
        f"#define ANIM_CLUSTER_ID {schema['cluster_id']}",
    ]
    for name, val in attrs.items():
        c_lines.append(f"#define ANIM_ATTR_{name.upper()} {val}")
    c_lines += [
        f"#define ANIM_CHUNK_MAX_BYTES {schema['chunk_max_bytes']}",
        "",
        _c_struct("anim_chunk_hdr_t", schema["frame_chunk_header"]),
        "",
        _c_struct("anim_transfer_meta_t", schema["transfer_meta"]),
        "",
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "",
    ]

    py_lines = [
        "# AUTO-GENERATED by tools/generate_wire.py from shared/wire_contract.json - DO NOT EDIT.",
        f"CLUSTER_ID = {schema['cluster_id']}",
    ]
    for name, val in attrs.items():
        py_lines.append(f"ATTR_{name.upper()} = {val}")
    py_lines += [
        f"MAX_CHUNK_BYTES = {schema['chunk_max_bytes']}",
        f"CHUNK_HEADER_FMT = \"<{''.join(PY_FMT[t] for _, t in schema['frame_chunk_header'])}\"",
        f"META_FMT = \"<{''.join(PY_FMT[t] for _, t in schema['transfer_meta'])}\"",
        "",
    ]

    return "\n".join(c_lines), "\n".join(py_lines)


def main():
    with open(SCHEMA) as f:
        schema = json.load(f)
    c_src, py_src = generate(schema)
    os.makedirs(os.path.dirname(C_OUT), exist_ok=True)
    os.makedirs(os.path.dirname(PY_OUT), exist_ok=True)
    with open(C_OUT, "w") as f:
        f.write(c_src)
    with open(PY_OUT, "w") as f:
        f.write(py_src)
    print(f"wrote {C_OUT}")
    print(f"wrote {PY_OUT}")


if __name__ == "__main__":
    main()
