name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  test:
    uses: ./.github/workflows/tools.yml

  firmware:
    needs: test
    uses: ./.github/workflows/build.yml
    with:
      release: true
      version: ${{ github.ref_name }}
